version: "3"
services: 
  postgres: 
    image: 'postgres:latest'
    ports: 
     - '5435:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: concurrency
  redis: 
    image: 'redis:alpine'
    ports: 
      - "6379:6379"
    restart: always


  mailhog: 
    image: 'mailhog/mailhog:latest' 
    ports: 
      - "1025:1025"
      - "8025:8025"
    restart: always        